{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "agent-operator.fullname" . }}-agent-pods
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      agents.wearn.dev/pod-type: agent-runner
  policyTypes:
  - Egress
  egress:
  {{- toYaml .Values.networkPolicy.egress | nindent 2 }}
{{- end }}
